//Product data
const products = [
    {
        id: 10001,
        name: "Men Black Kurta Pant Set",
        category: "Men",
        price: { S: 1100, M: 1200, L: 1200, XL: 1300, XXL: 1300 },
        color: "black",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_kurta_pant_set/men_black_kurta_pant_set.jpeg",
    },
    {
        id: 10002,
        name: "Men Blue Kurta Pant Set",
        category: "Men",
        price: { S: 1100, M: 1200, L: 1200, XL: 1300, XXL: 1300 },
        color: "blue",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_kurta_pant_set/men_blue_kurta_pant_set.jpeg",
    },
    {
        id: 10003,
        name: "Men Green Kurta Pant Set",
        category: "Men",
        price: { S: 1100, M: 1200, L: 1200, XL: 1300, XXL: 1300 },
        color: "green",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_kurta_pant_set/men_green_kurta_pant_set.jpeg",
    },
    {
        id: 10004,
        name: "Men Pink Kurta Pant Set",
        category: "Men",
        price: { S: 1100, M: 1200, L: 1200, XL: 1300, XXL: 1300 },
        color: "pink",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_kurta_pant_set/men_pink_kurta_pant_set.jpeg",
    },
    {
        id: 10005,
        name: "Men Navy Blue Kurta Pant Set",
        category: "Men",
        price: { S: 1100, M: 1200, L: 1200, XL: 1300, XXL: 1300 },
        color: "navy blue",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_kurta_pant_set/men_navyblue_kurta_pant_set.jpeg",
    },
    {
        id: 10006,
        name: "Men Red Kurta Pant Set",
        category: "Men",
        price: { S: 1100, M: 1200, L: 1200, XL: 1300, XXL: 1300 },
        color: "red",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_kurta_pant_set/men_red_kurta_pant_set.jpeg",
    },
    {
        id: 10007,
        name: "Men White Kurta Pant Set",
        category: "Men",
        price: { S: 1100, M: 1200, L: 1200, XL: 1300, XXL: 1300 },
        color: "white",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_kurta_pant_set/men_white_kurta_pant_set.jpeg",
    },

    {
        id: 10008,
        name: "Men Black Sherwani Pant Set",
        category: "Men",
        price: { S: 1400, M: 1500, XL: 1700, XXL: 1700 },
        color: "black",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_sherwani_pant_set/men_black_sherwani_pant_set.jpeg",
    },
    {
        id: 10009,
        name: "Men Green Sherwani Pant Set",
        category: "Men",
        price: { S: 1400, M: 1500, XL: 1700, XXL: 1700 },
        color: "green",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_sherwani_pant_set/men_green_sherwani_pant_set.jpeg",
    },
    {
        id: 10010,
        name: "Men Light Blue Sherwani Pant Set",
        category: "Men",
        price: { S: 1400, M: 1500, XL: 1700, XXL: 1700 },
        color: "lightblue",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_sherwani_pant_set/men_lightblue_sherwani_pant_set.jpeg",
    },
    {
        id: 10011,
        name: "Men Navy Blue Sherwani Pant Set",
        category: "Men",
        price: { S: 1400, M: 1500, XL: 1700, XXL: 1700 },
        color: "navyblue",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_sherwani_pant_set/men_navyblue_sherwani_pant_set.jpeg",
    },
    {
        id: 10012,
        name: "Men Pink Sherwani Pant Set",
        category: "Men",
        price: { S: 1400, M: 1500, XL: 1700, XXL: 1700 },
        color: "pink",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_sherwani_pant_set/men_pink_sherwani_pant_set.jpeg",
    },
    {
        id: 10013,
        name: "Men Purple Sherwani Pant Set",
        category: "Men",
        price: { S: 1400, M: 1500, XL: 1700, XXL: 1700 },
        color: "purple",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_sherwani_pant_set/men_purple_sherwani_pant_set.jpeg",
    },
    {
        id: 10014,
        name: "Men Red Sherwani Pant Set",
        category: "Men",
        price: { S: 1400, M: 1500, XL: 1700, XXL: 1700 },
        color: "red",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_sherwani_pant_set/men_red_sherwani_pant_set.jpeg",
    },
    {
        id: 10015,
        name: "Men White Sherwani Pant Set",
        category: "Men",
        price: { S: 1400, M: 1500, XL: 1700, XXL: 1700 },
        color: "white",
        size: ["S", "M", "L", "XL", "XXL"],
        image: "images/men/men_sherwani_pant_set/men_white_sherwani_pant_set.jpeg",
    },
    {
        id: 10016,
        name: "Women Black Anarkali Pant Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, XL: 1400, XXL: 1400 },
        color: "black",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_anarkali_pant_set/women_black_anarkali_pant_dupatta_set.jpeg",
    },
    {
        id: 10017,
        name: "Women Green Anarkali Pant Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, XL: 1400, XXL: 1400 },
        color: "green",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_anarkali_pant_set/women_green_anarkali_pant_dupatta_set.jpeg",
    },
    {
        id: 10018,
        name: "Women Light Blue Anarkali Pant Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, XL: 1400, XXL: 1400 },
        color: "lightblue",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_anarkali_pant_set/women_lightblue_anarkali_pant_dupatta_set.jpeg",
    },
    {
        id: 10019,
        name: "Women Navy Blue Anarkali Pant Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, XL: 1400, XXL: 1400 },
        color: "navyblue",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_anarkali_pant_set/women_navyblue_anarkali_pant_dupatta_set.jpeg",
    },
    {
        id: 10020,
        name: "Women Orange Anarkali Pant Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, XL: 1400, XXL: 1400 },
        color: "orange",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_anarkali_pant_set/women_orange_anarkali_pant_dupatta_set.jpeg",
    },
    {
        id: 10021,
        name: "Women Pink Anarkali Pant Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, XL: 1400, XXL: 1400 },
        color: "pink",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_anarkali_pant_set/women_pink_anarkali_pant_dupatta_set.jpeg",
    },
    {
        id: 10022,
        name: "Women Red Anarkali Pant Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, XL: 1400, XXL: 1400 },
        color: "red",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_anarkali_pant_set/women_red_anarkali_pant_dupatta_set.jpeg",
    },
    {
        id: 10023,
        name: "Women White Anarkali Pant Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, XL: 1400, XXL: 1400 },
        color: "white",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_anarkali_pant_set/women_white_anarkali_dupatta_set.jpeg",
    },

    {
        id: 10024,
        name: "Women Black Gown",
        category: "Women",
        price: { XS: 1000, S: 1000, M: 1100, XL: 1200, XXL: 1200 },
        color: "black",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_gown/women_black_gown.jpeg",
    },
    {
        id: 10025,
        name: "Women Green Gown",
        category: "Women",
        price: { XS: 1000, S: 1000, M: 1100, XL: 1200, XXL: 1200 },
        color: "green",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_gown/women_green_gown.jpeg",
    },
    {
        id: 10026,
        name: "Women Light Blue Gown",
        category: "Women",
        price: { XS: 1000, S: 1000, M: 1100, XL: 1200, XXL: 1200 },
        color: "lightblue",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_gown/women_lightblue_gown.jpeg",
    },
    {
        id: 10027,
        name: "Women Pink Gown",
        category: "Women",
        price: { XS: 1000, S: 1000, M: 1100, XL: 1200, XXL: 1200 },
        color: "pink",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_gown/women_pink_gown.jpeg",
    },
    {
        id: 10028,
        name: "Women Purple Gown",
        category: "Women",
        price: { XS: 1000, S: 1000, M: 1100, XL: 1200, XXL: 1200 },
        color: "purple",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_gown/women_purple_gown.jpeg",
    },
    {
        id: 10029,
        name: "Women Red Gown",
        category: "Women",
        price: { XS: 1000, S: 1000, M: 1100, XL: 1200, XXL: 1200 },
        color: "red",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_gown/women_red_gown.jpeg",
    },
    {
        id: 10030,
        name: "Women White Gown",
        category: "Women",
        price: { XS: 1000, S: 1000, M: 1100, XL: 1200, XXL: 1200 },
        color: "white",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_gown/women_white_gown.jpeg",
    },
    {
        id: 10031,
        name: "Women Yellow Gown",
        category: "Women",
        price: { XS: 1000, S: 1000, M: 1100, XL: 1200, XXL: 1200 },
        color: "yellow",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_gown/women_yellow_gown.jpeg",
    },
    
    {
        id: 10032,
        name: "Women Black Lehenga Choli Set",
        category: "Women",
        price: { XS: 1000, S: 1000, M: 1100, XL: 1200, XXL: 1200 },
        color: "black",
        size: ["XS", "S", "M", "L", "XL"],
        image: "images/women/women_lehenga_choli_set/women_black_lehenga_choli_dupatta_set.jpeg",
    },
    {
        id: 10033,
        name: "Women Blue Lehenga Choli Set",
        category: "Women",
        price: { XS: 1800, S: 1800, M: 1900, L: 1900, XL: 2000, XXL: 2000 },
        color: "blue",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_lehenga_choli_set/women_blue_lehenga_choli_dupatta_set.jpeg",
    },
    {
        id: 10034,
        name: "Women Green Lehenga Choli Set",
        category: "Women",
        price: { XS: 1800, S: 1800, M: 1900, L: 1900, XL: 2000, XXL: 2000 },
        color: "green",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_lehenga_choli_set/women_green_lehenga_choli_dupatta_set.jpeg",
    },
    {
        id: 10035,
        name: "Women Navy Blue Lehenga Choli Set",
        category: "Women",
        price: { XS: 1800, S: 1800, M: 1900, L: 1900, XL: 2000, XXL: 2000 },
        color: "navy blue",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_lehenga_choli_set/women_navyblue_lehenga_choli_dupatta_set.jpeg",
    },
    {
        id: 10036,
        name: "Women Pink Lehenga Choli Set",
        category: "Women",
        price: { XS: 1800, S: 1800, M: 1900, L: 1900, XL: 2000, XXL: 2000 },
        color: "pink",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_lehenga_choli_set/women_pink_lehenga_choli_dupatta_set.jpeg",
    },
    {
        id: 10037,
        name: "Women Red Lehenga Choli Set",
        category: "Women",
        price: { XS: 1800, S: 1800, M: 1900, L: 1900, XL: 2000, XXL: 2000 },
        color: "red",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_lehenga_choli_set/women_red_lehenga_choli_dupatta_set.jpeg",
    },
    {
        id: 10038,
        name: "Women White Lehenga Choli Set",
        category: "Women",
        price: { XS: 1800, S: 1800, M: 1900, L: 1900, XL: 2000, XXL: 2000 },
        color: "white",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_lehenga_choli_set/women_white_lehenga_choli_dupatta_set.jpeg",
    },
    {
        id: 10039,
        name: "Women Yellow Lehenga Choli Set",
        category: "Women",
        price: { XS: 1800, S: 1800, M: 1900, L: 1900, XL: 2000, XXL: 2000 },
        color: "yellow",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_lehenga_choli_set/women_yellow_lehenga_choli_dupatta_set.jpeg",
    },
    {
        id: 10040,
        name: "Women Black Salwar Kameez Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, L: 1400, XL: 1400, XXL: 1500 },
        color: "black",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_salwar_kameez_set/women_black_salwar_kameez_set.jpeg",
    },
    {
        id: 10041,
        name: "Women Green Salwar Kameez Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, L: 1400, XL: 1400, XXL: 1500 },
        color: "green",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_salwar_kameez_set/women_green_salwar_kameez_set.jpeg",
    },
    {
        id: 10042,
        name: "Women Orange Salwar Kameez Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, L: 1400, XL: 1400, XXL: 1500 },
        color: "orange",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_salwar_kameez_set/women_orange_salwar_kameez_set.jpeg",
    },
    {
        id: 10043,
        name: "Women Pink Salwar Kameez Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, L: 1400, XL: 1400, XXL: 1500 },
        color: "pink",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_salwar_kameez_set/women_pink_salwar_kameez_set.jpeg",
    },
    {
        id: 10044,
        name: "Women Purple Salwar Kameez Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, L: 1400, XL: 1400, XXL: 1500 },
        color: "purple",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_salwar_kameez_set/women_purple_salwar_kameez_set.jpeg",
    },
    {
        id: 10045,
        name: "Women Red Salwar Kameez Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, L: 1400, XL: 1400, XXL: 1500 },
        color: "red",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_salwar_kameez_set/women_red_salwar_kameez_set.jpeg",
    },
    {
        id: 10046,
        name: "Women White Salwar Kameez Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, L: 1400, XL: 1400, XXL: 1500 },
        color: "white",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_salwar_kameez_set/women_white_salwar_kameez_set.jpeg",
    },
    {
        id: 10047,
        name: "Women Yellow Salwar Kameez Set",
        category: "Women",
        price: { XS: 1200, S: 1200, M: 1300, L: 1400, XL: 1400, XXL: 1500 },
        color: "yellow",
        size: ["XS", "S", "M", "L", "XL", "XXL"],
        image: "images/women/women_salwar_kameez_set/women_yellow_salwar_kameez_set.jpeg",
    },
    {
        "id": 10048,
        "name": "Boys Black Kurta Pajama Set",
        "category": "Boys",
        "price": { "1-2 years": 500, "3-5 years": 500, "6-8 years": 700, "9-12 years": 700, "13-16 years": 800 },
        "color": "Black",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_kurta_pajama_set/boys_black_kurta_pajama_set.jpeg"
    },
    {
        "id": 10049,
        "name": "Boys Green Kurta Pajama Set",
        "category": "Boys",
        "price": { "1-2 years": 500, "3-5 years": 500, "6-8 years": 700, "9-12 years": 700, "13-16 years": 800 },
        "color": "Green",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_kurta_pajama_set/boys_green_kurta_pajama_set.jpeg"
    },
    {
        "id": 10050,
        "name": "Boys Grey Kurta Pajama Set",
        "category": "Boys",
        "price": { "1-2 years": 500, "3-5 years": 500, "6-8 years": 700, "9-12 years": 700, "13-16 years": 800 },
        "color": "Grey",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_kurta_pajama_set/boys_grey_kurta_pajama_set.jpeg"
    },
    {
        "id": 10051,
        "name": "Boys Light Blue Kurta Pajama Set",
        "category": "Boys",
        "price": { "1-2 years": 500, "3-5 years": 500, "6-8 years": 700, "9-12 years": 700, "13-16 years": 800 },
        "color": "Light Blue",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_kurta_pajama_set/boys_lightblue_kurta_pajama_set.jpeg"
    },
    {
        "id": 10052,
        "name": "Boys Navy Blue Kurta Pajama Set",
        "category": "Boys",
        "price": { "1-2 years": 500, "3-5 years": 500, "6-8 years": 700, "9-12 years": 700, "13-16 years": 800 },
        "color": "Navy Blue",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_kurta_pajama_set/boys_navyblue_kurta_pajama_set.jpeg"
    },
    {
        "id": 10053,
        "name": "Boys Pink Kurta Pajama Set",
        "category": "Boys",
        "price": { "1-2 years": 500, "3-5 years": 500, "6-8 years": 700, "9-12 years": 700, "13-16 years": 800 },
        "color": "Pink",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_kurta_pajama_set/boys_pink_kurta_pajama_set.jpeg"
    },
    {
        "id": 10054,
        "name": "Boys Red Kurta Pajama Set",
        "category": "Boys",
        "price": { "1-2 years": 500, "3-5 years": 500, "6-8 years": 700, "9-12 years": 700, "13-16 years": 800 },
        "color": "Red",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_kurta_pajama_set/boys_red_kurta_pajama_set.jpeg"
    },
    {
        "id": 10055,
        "name": "Boys Yellow Kurta Pajama Set",
        "category": "Boys",
        "price": { "1-2 years": 500, "3-5 years": 500, "6-8 years": 700, "9-12 years": 700, "13-16 years": 800 },
        "color": "Yellow",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_kurta_pajama_set/boys_yellow_kurta_pajama_set.jpeg"
    },

    {
        "id": 10056,
        "name": "Boys Black Sherwani Pant Set",
        "category": "Boys",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 900, "9-12 years": 1000, "13-16 years": 1100 },
        "color": "Black",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_sherwani_pant_set/boys_black_sherwani_pant_set.jpeg"
    },
    {
        "id": 10057,
        "name": "Boys Green Sherwani Pant Set",
        "category": "Boys",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 900, "9-12 years": 1000, "13-16 years": 1100 },
        "color": "Green",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_sherwani_pant_set/boys_green_sherwani_pant_set.jpeg"
    },
    {
        "id": 10058,
        "name": "Boys Lavender Sherwani Pant Set",
        "category": "Boys",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 900, "9-12 years": 1000, "13-16 years": 1100 },
        "color": "Lavender",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_sherwani_pant_set/boys_lavender_sherwani_pant_set.jpeg"
    },
    {
        "id": 10059,
        "name": "Boys Light Blue Sherwani Pant Set",
        "category": "Boys",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 900, "9-12 years": 1000, "13-16 years": 1100 },
        "color": "Light Blue",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_sherwani_pant_set/boys_lightblue_sherwani_pant_set.jpeg"
    },
    {
        "id": 10060,
        "name": "Boys Maroon Sherwani Pant Set",
        "category": "Boys",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 900, "9-12 years": 1000, "13-16 years": 1100 },
        "color": "Maroon",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_sherwani_pant_set/boys_maroon_sherwani_pant_set.jpeg"
    },
    {
        "id": 10061,
        "name": "Boys Orange Sherwani Pant Set",
        "category": "Boys",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 900, "9-12 years": 1000, "13-16 years": 1100 },
        "color": "Orange",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_sherwani_pant_set/boys_orange_sherwani_pant_set.jpeg"
    },
    {
        "id": 10062,
        "name": "Boys White Sherwani Pant Set",
        "category": "Boys",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 900, "9-12 years": 1000, "13-16 years": 1100 },
        "color": "White",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_sherwani_pant_set/boys_white_sherwani_pant_set.jpeg"
    },
    {
        "id": 10063,
        "name": "Boys Yellow Sherwani Pant Set",
        "category": "Boys",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 900, "9-12 years": 1000, "13-16 years": 1100 },
        "color": "Yellow",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/boys/boys_sherwani_pant_set/boys_yellow_sherwani_pant_set.jpeg"
    },

    {
        "id": 10064,
        "name": "Girls Blue Gown",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 900, "13-16 years": 1000 },
        "color": "Blue",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_gown/girls_blue_gown.jpg"
    },
    {
        "id": 10065,
        "name": "Girls Green Gown",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 900, "13-16 years": 1000 },
        "color": "Green",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_gown/girls_green_gown.jpeg"
    },
    {
        "id": 10066,
        "name": "Girls Maroon Gown",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 900, "13-16 years": 1000 },
        "color": "Maroon",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_gown/girls_maroon_gown.jpeg"
    },
    {
        "id": 10067,
        "name": "Girls Navy Blue Gown",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 900, "13-16 years": 1000 },
        "color": "Navy Blue",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_gown/girls_navyblue_gown.jpeg"
    },
    {
        "id": 10068,
        "name": "Girls Orange Gown",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 900, "13-16 years": 1000 },
        "color": "Orange",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_gown/girls_orange_gown.jpeg"
    },
    {
        "id": 10069,
        "name": "Girls Purple Gown",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 900, "13-16 years": 1000 },
        "color": "Purple",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_gown/girls_purple_gown.jpeg"
    },
    {
        "id": 10070,
        "name": "Girls Red Gown",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 900, "13-16 years": 1000 },
        "color": "Red",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_gown/girls_red_gown.jpeg"
    },
    {
        "id": 10071,
        "name": "Girls Yellow Gown",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 900, "13-16 years": 1000 },
        "color": "Yellow",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_gown/girls_yellow_gown.jpeg"
    },

    {
        "id": 10072,
        "name": "Girls Blue Lehenga Choli Set",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 1000, "13-16 years": 1200 },
        "color": "Blue",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_lehenga_choli_set/girls_blue_lehenga_choli_set.jpeg"
    },
    {
        "id": 10073,
        "name": "Girls Golden Lehenga Choli Set",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 1000, "13-16 years": 1200 },
        "color": "Golden",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_lehenga_choli_set/girls_golden_lehenga_choli_set.jpeg"
    },
    {
        "id": 10074,
        "name": "Girls Green Lehenga Choli Set",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 1000, "13-16 years": 1200 },
        "color": "Green",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_lehenga_choli_set/girls_green_lehenga_choli_set.jpeg"
    },
    {
        "id": 10075,
        "name": "Girls Grey Lehenga Choli Set",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 1000, "13-16 years": 1200 },
        "color": "Grey",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_lehenga_choli_set/girls_grey_lehenga_choli_set.jpeg"
    },
    {
        "id": 10076,
        "name": "Girls Pink Lehenga Choli Set",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 1000, "13-16 years": 1200 },
        "color": "Pink",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_lehenga_choli_set/girls_pink_lehenga_choli_set.jpeg"
    },
    {
        "id": 10077,
        "name": "Girls Purple Lehenga Choli Set",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 1000, "13-16 years": 1200 },
        "color": "Purple",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_lehenga_choli_set/girls_purple_lehenga_choli_set.jpeg"
    },
    {
        "id": 10078,
        "name": "Girls Red Lehenga Choli Set",
        "category": "Girls",
        "price": { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 1000, "13-16 years": 1200 },
        "color": "Red",
        "size": ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        "image": "images/girls/girls_lehenga_choli_set/girls_red_lehenga_choli_set.jpeg"
    },
    {
        id: 10079,
        name: "Girls White Lehenga Choli Set",
        category: "Girls",
        price: { "1-2 years": 600, "3-5 years": 700, "6-8 years": 800, "9-12 years": 1000, "13-16 years": 1200 },
        color: "White",
        size: ["1-2 years", "3-5 years", "6-8 years", "9-12 years", "13-16 years"],
        image: "images/girls/girls_lehenga_choli_set/girls_white_lehenga_choli_set.jpeg"
    }
];